export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as MenuPage } from './MenuPage';
export { default as CartPage } from './CartPage';
export { default as BookingPage } from './BookingPage';
export { default as CheckoutPage } from './CheckoutPage';
export { default as OrderConfirmationPage } from './OrderConfirmationPage';
export { default as AccountPage } from './AccountPage';
