"""
Calculation document model for the CALC Scientific Calculator.

Defines the document schema and factory function for creating
calculation entries in the MongoDB calculation_history collection.

Document Schema (MongoDB):
    {
        "_id": ObjectId (auto-generated by MongoDB on insert),
        "user_id": str — Auth0 'sub' claim identifying the user,
        "expression": str — the calculation expression (e.g. "2+3", "sin(45)"),
        "result": float — the computed numeric result,
        "operation_type": str — "standard" or "scientific",
        "scientific_function": str | None — e.g. "sin", "cos", "log", or None,
        "angle_unit": str | None — "degrees", "radians", or None,
        "created_at": datetime (UTC) — when the calculation was performed,
        "expires_at": datetime (UTC) — TTL expiration timestamp
    }

The _id field is NOT produced by the factory; MongoDB generates it on insertion.
"""

from datetime import datetime, timedelta, timezone

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_HISTORY_TTL_DAYS: int = 90
"""Default number of days before a history entry expires and is automatically
removed by the MongoDB TTL index.  Per AAP Section 0.7.3 the configurable
default is 90 days."""

VALID_OPERATION_TYPES: tuple[str, ...] = ("standard", "scientific")
"""Permitted values for the ``operation_type`` field.  Every calculation is
classified as either a basic-arithmetic *standard* operation or a
*scientific* operation (trig, log, power, factorial, etc.)."""

VALID_ANGLE_UNITS: tuple[str, ...] = ("degrees", "radians")
"""Permitted values for the ``angle_unit`` field when it is not ``None``.
Trigonometric calculations must specify whether the operand is in degrees
or radians.  Non-trigonometric calculations pass ``None``."""


# ---------------------------------------------------------------------------
# Factory function
# ---------------------------------------------------------------------------

def create_calculation_document(
    user_id: str,
    expression: str,
    result: float,
    operation_type: str,
    scientific_function: str | None = None,
    angle_unit: str | None = None,
    ttl_days: int = DEFAULT_HISTORY_TTL_DAYS,
) -> dict:
    """Create a calculation document dict ready for MongoDB insertion.

    This factory validates inputs, generates UTC-aware timestamps, and
    returns a dictionary whose keys map 1-to-1 to the fields stored in
    the ``calculation_history`` MongoDB collection.  The ``_id`` field is
    intentionally omitted — MongoDB assigns it automatically on
    ``insert_one()``.

    Parameters
    ----------
    user_id : str
        Auth0 ``sub`` claim that uniquely identifies the user.  The
        calling layer (middleware / route) is responsible for extracting
        this value from the verified JWT.
    expression : str
        Human-readable calculation expression, e.g. ``"2+3"`` or
        ``"sin(45)"``.
    result : float
        The numeric computation result.
    operation_type : str
        Must be one of :data:`VALID_OPERATION_TYPES` (``"standard"`` or
        ``"scientific"``).
    scientific_function : str or None, optional
        The specific scientific function applied (e.g. ``"sin"``,
        ``"cos"``, ``"log"``).  ``None`` for standard arithmetic.
    angle_unit : str or None, optional
        ``"degrees"`` or ``"radians"`` for trigonometric operations.
        ``None`` for non-trigonometric calculations.
    ttl_days : int, optional
        Number of days until the document expires (default
        :data:`DEFAULT_HISTORY_TTL_DAYS` = 90).  The resulting
        ``expires_at`` timestamp drives the MongoDB TTL index.

    Returns
    -------
    dict
        A document dict containing exactly eight keys: ``user_id``,
        ``expression``, ``result``, ``operation_type``,
        ``scientific_function``, ``angle_unit``, ``created_at``, and
        ``expires_at``.

    Raises
    ------
    ValueError
        If *operation_type* is not in :data:`VALID_OPERATION_TYPES`.
    ValueError
        If *angle_unit* is not ``None`` and not in
        :data:`VALID_ANGLE_UNITS`.
    ValueError
        If *user_id* or *expression* is an empty string.
    TypeError
        If *ttl_days* is not an integer.

    Examples
    --------
    >>> doc = create_calculation_document(
    ...     user_id="auth0|abc123",
    ...     expression="2+3",
    ...     result=5.0,
    ...     operation_type="standard",
    ... )
    >>> sorted(doc.keys())
    ['angle_unit', 'created_at', 'expires_at', 'expression', 'operation_type', 'result', 'scientific_function', 'user_id']

    >>> doc = create_calculation_document(
    ...     user_id="auth0|abc123",
    ...     expression="sin(45)",
    ...     result=0.7071067811865476,
    ...     operation_type="scientific",
    ...     scientific_function="sin",
    ...     angle_unit="degrees",
    ... )
    >>> doc["operation_type"]
    'scientific'
    """

    # ------------------------------------------------------------------
    # Input validation
    # ------------------------------------------------------------------

    # Validate required string fields are non-empty
    if not isinstance(user_id, str) or not user_id.strip():
        raise ValueError("user_id must be a non-empty string.")

    if not isinstance(expression, str) or not expression.strip():
        raise ValueError("expression must be a non-empty string.")

    # Validate operation_type against the allowed set
    if operation_type not in VALID_OPERATION_TYPES:
        raise ValueError(
            f"Invalid operation_type: {operation_type}. "
            f"Must be one of {VALID_OPERATION_TYPES}"
        )

    # Validate angle_unit — None is perfectly acceptable (non-trig ops)
    if angle_unit is not None and angle_unit not in VALID_ANGLE_UNITS:
        raise ValueError(
            f"Invalid angle_unit: {angle_unit}. "
            f"Must be one of {VALID_ANGLE_UNITS} or None"
        )

    # Validate ttl_days is a positive integer
    if not isinstance(ttl_days, int):
        raise TypeError(
            f"ttl_days must be an integer, got {type(ttl_days).__name__}."
        )
    if ttl_days <= 0:
        raise ValueError("ttl_days must be a positive integer.")

    # ------------------------------------------------------------------
    # Timestamp generation (UTC-aware)
    # ------------------------------------------------------------------

    now: datetime = datetime.now(timezone.utc)
    expires_at: datetime = now + timedelta(days=ttl_days)

    # ------------------------------------------------------------------
    # Construct and return the document dict
    # ------------------------------------------------------------------

    return {
        "user_id": user_id,
        "expression": expression,
        "result": result,
        "operation_type": operation_type,
        "scientific_function": scientific_function,
        "angle_unit": angle_unit,
        "created_at": now,
        "expires_at": expires_at,
    }
